config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  resources :products, only: %i[show index] do
    member do
      post :cart, to: 'products#add_to_cart'
      delete :cart, to: 'products#remove_from_cart'
      patch :cart, to: 'products#change_count_in_cart'
    end

    collection do
      get :cart
    end
  end

  resources :orders, only: %i[new create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
  accepts_nested_attributes_for :order_products
  belongs_to :user
  accepts_nested_attributes_for :user
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_cart

  def current_cart
    @current_cart ||= if session[:cart_id]
                        Cart.find(session[:cart_id])
                      else
                        cart = Cart.create!
                        session[:cart_id] = cart.id
                        cart
                      end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @order.build_user
    current_cart.cart_products.each do |cart_product|
      @order.order_products.build(
        product_id: cart_product.product_id,
        count: cart_product.count,
        price: cart_product.product.price
      )
    end
  end

  def create
    @order = Order.create(order_params)
    if @order.save
      redirect_to root_path
    else
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:delivery_type, :payment_type, :address, :description,
                                  user_attributes: %i[name phone email], order_products_attributes: %i[product_id count price])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @products = Product.limit(6).with_attached_image
    pp request.env['HTTP_USER_AGENT']
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :product, only: [:show]

  def index
    @products = Product.all.with_attached_image
  end

  def show
    @products = Product.limit(3).with_attached_image
  end

  def add_to_cart
    if cart_product = current_cart.cart_products.find_by(product_id: product.id)
      cart_product.update(count: cart_product.count.to_i + 1)
    else
      new_cart_product = current_cart.cart_products.build(product: product, count: 1)
      new_cart_product.save
    end
    respond_to do |format|
      format.json { render json: '' }
    end
  end

  def remove_from_cart
    if cart_product = current_cart.cart_products.find_by(product_id: product.id)
      cart_product.delete
    end
    respond_to do |format|
      format.json { render json: '' }
    end
  end

  def change_count_in_cart
    if cart_product = current_cart.cart_products.find_by(product_id: product.id)
      cart_product.update(count: params[:count])
    end
    respond_to do |format|
      format.json { render json: '' }
    end
  end

  def cart
    @products = current_cart.cart_products.includes(product: [image_attachment: [:blob]])
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def product
    @product ||= Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<footer>
Footer
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Home", root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "Каталог", products_path, class:"nav-link"%>
        </li>
      </ul>
      <span class="navbar-text">
        <span id="cart" onclick="show_cart()">Кошик</span>
      </span>


    </div>
  </div>
</nav>
<div class="modal fade" id="cart_modal" tabindex="-1" aria-labelledby="cart_modalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content modal-dialog-scrollable">
      <div class="modal-header">
        <h5 class="modal-title" id="cart_modalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body row" id="cart_body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= link_to "Order", new_order_path,class:"btn btn-succsess"%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <div class="container pt-4">
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/orders/new.html.erb
<%= simple_form_for @order do |f|%>
<%= f.simple_fields_for :user do |u_f|%>
<div class="card">
  <div class="card-body">
User params
<%= u_f.input :name%>
<%= u_f.input :phone%>
<%= u_f.input :email%>
</div>
</div>
<%end%>
<%= f.input :delivery_type%>
<%= f.input :payment_type%>

<%= f.input :address%>
<%= f.input :description,as: :text%>

<%= f.simple_fields_for :order_products do |o_p_f|%>
<%= o_p_f.object.product.name%>
<%= image_tag o_p_f.object.product&.image %>

<%= o_p_f.input :count%>
<%= o_p_f.input :product_id, as: :hidden%>
<%= o_p_f.input :price, as: :hidden%>
<%end%>
Ціна за все
<%= f.submit :order %>
<%end%>

app/views/pages/index.html.erb
<h1 class="title">SHOP</h1>
<div class="row g-3">
  <%= render ProductComponent.with_collection(@products)%>
</div>

app/views/products/cart.js.erb
var cart_body =document.getElementById('cart_body')
cart_body.innerHTML = '<%=j render  Cart::ProductComponent.with_collection(@products)%>'

app/views/products/index.html.erb
<h1 class="title">CATALOGUE</h1>
<div class="row g-3">
  <%= render ProductComponent.with_collection(@products)%>
</div>

app/views/products/show.html.erb
<div class="product">
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= image_tag @product.image, alt:@product.name, title:@product.name, class:"image"%>
    </div>
    <div class="col-12 col-lg-6">

      <h1 class="title">
        <%= @product.name%>
      </h1>
      <p><%= @product.description%></p>
      <div class="btn btn-danger" onclick="add_to_cart(<%=@product.id%>)">
        Add to cart
      </div>
    </div>
  </div>
</div>
<section class="other-products mt-5">
<h2 class="text-center">OTHERS</h2>
<div class="row">
  <%= render ProductComponent.with_collection(@products)%>
</div>
</section>